### PR TITLE
Provide a Buster based image compatible with raspbian < bullseye

### PR DESCRIPTION
**Pull request by sidey79**
1. Create a image based on buster  #40 

2. Create additional bullseye based Image.

3. NPM Modules excluded due to errors with one of those packages

4. Tag names changed to identify the base image

### CODE REVIEW

**Comment by git-developer** [comment]
Thanks for your efforts!

The image comes up without problems on a Raspberry Pi 3 Model B running Raspbian Buster (Kernel 5.10.63-v7+, Docker 18.09.1, libseccomp2 2.3.3-4).

On my system it works flawlessly, the same as the current `latest` build from Docker Hub does.

**Comment by sidey79** [comment]
@git-developer 

Thanks for your feedback. I tested it also on an PI2 stretch with Kernel 4.19.66-v7+, Docker '5:19.03', libseccomp2  2.3.1-2.1.


Do you have still the same problem as mentioned in #40  ?

**Comment by git-developer** [comment]
Yes, the behavior remains unchanged: Jabber is broken unless `libauthen-sasl-cyrus-perl` is removed.

**Comment by sidey79** [comment]
@jpawlowski 

Do you have any idea for what this package is installed per default?
I could not find any hint in the fhem forum.

**Comment by jpawlowski** [comment]
I don't think there is a particular reason.
The original dockerfile had some wildcard package inclusions for libs that might be important or relevant. Obviously this can be true for authentication libs in general which IIRC was why they were included in the first place.

**Pull request merged**
