### PR TITLE
Add Crypt::Random installation

### PR DESCRIPTION
**Pull request by donjonsn**
Explicitly install Crypt::Random for EnOcean encryption support. The Perl package depends on Math::Pari and Class::Loader.

fhem logs: EnOcean Cryptographic functions are not available.

fhem check:
# perl -e "use Crypt::Random qw(makerandom)"
Can't locate Crypt/Random.pm in @INC (you may need to install the Crypt::Random module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at -e line 1.
BEGIN failed--compilation aborted at -e line 1.

### CODE REVIEW

**Comment by bruzzz** [comment]
Hi, I just ran in the same problem.

I had a look at the code in the Dockerfile but I'm little confused. I can't find the code introduced with this fix in the current version.

I also tried to just add the missing modules with the container configuration (setting the environment variable CPAN_PKGS). But this doesn't work. When I login into the running container and check wit cpan -l those modules are missing. Installing manually in the container takes some time and requires additional confirmation, but works. So I'm wondering, what's going on there and if / where I could check, why the modules are not installed when they are defined with the CPAN_PKGS environment variable?

I'm strugling with that on an ARMv8 64bit.

**Comment by bruzzz** [comment]
I looked a little further through the code and identified, where the logs are written to (/pkgs.*).

If my understanding is right, it lokks like a timeout issue (if I do the same manually / interactivly it works fine):
```bash
# cat /pkgs.cpanm 
Class::Loader is up to date. (2.03)
--> Working on Math::Pari
Fetching http://www.cpan.org/authors/id/I/IL/ILYAZ/modules/Math-Pari-2.030518.zip ... OK
Configuring Math-Pari-2.030518 ... ! Timed out (> 60s). Use --verbose to retry.
! Configure failed for Math-Pari-2.030518. See /root/.cpanm/work/1613073570.402/build.log for details.
FAIL
--> Working on Crypt::Random
Fetching http://www.cpan.org/authors/id/V/VI/VIPUL/Crypt-Random-1.52.tar.gz ... OK
Configuring Crypt-Random-1.52 ... OK
==> Found dependencies: Math::Pari, Statistics::ChiSquare
--> Working on Statistics::ChiSquare
Fetching http://www.cpan.org/authors/id/D/DC/DCANTRELL/Statistics-ChiSquare-1.0000.tar.gz ... OK
Configuring Statistics-ChiSquare-1.0000 ... OK
Building Statistics-ChiSquare-1.0000 ... OK
Successfully installed Statistics-ChiSquare-1.0000
! Installing the dependencies failed: Module 'Math::Pari' is not installed
! Bailing out the installation for Crypt-Random-1.52.

# cat /root/.cpanm/work/1613073570.402/build.log
cpanm (App::cpanminus) 1.7044 on perl 5.028001 built for aarch64-linux-gnu-thread-multi
Work directory is /root/.cpanm/work/1613073570.402
You have make /usr/bin/make
You have LWP 6.36
You have /bin/tar: tar (GNU tar) 1.30
Copyright © 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Geschrieben von John Gilmore und Jay Fenlason.
You have /usr/bin/unzip
Searching Class::Loader () on cpanmetadb ...
Class::Loader is up to date. (2.03)
Searching Math::Pari () on cpanmetadb ...
--> Working on Math::Pari
Fetching http://www.cpan.org/authors/id/I/IL/ILYAZ/modules/Math-Pari-2.030518.zip
-> OK
Unpacking Math-Pari-2.030518.zip
Entering Math-Pari-2.030518
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring Math-Pari-2.030518
Running Makefile.PL
Did not find GP/PARI build directory around.
Non-interactive session, autofetching...

Getting GP/PARI from ftp://megrez.math.u-bordeaux.fr/pub/pari/
Cannot list (Illegal PORT command.
):  at utils/Math/PariBuild.pm line 456.

Can't fetch file with Net::FTP, now trying with LWP::UserAgent...
Not in this directory, trying `ftp://megrez.math.u-bordeaux.fr/pub/pari/unix/'...
Not in this directory, trying `ftp://megrez.math.u-bordeaux.fr/pub/pari/OLD/2.3/'...
Not in this directory, trying `ftp://megrez.math.u-bordeaux.fr/pub/pari/OLD/2.1/'...
Not in this directory, trying `ftp://megrez.math.u-bordeaux.fr/pub/pari/OLD/'...
Not in this directory, trying `http://megrez.math.u-bordeaux.fr/pub/pari/'...
Not in this directory, trying `http://megrez.math.u-bordeaux.fr/pub/pari/unix/'...
Not in this directory, trying `http://megrez.math.u-bordeaux.fr/pub/pari/OLD/2.3/'...
Available golden versions: `2.3.3 2.3.2 2.3.0 2.3.1 2.3.5 2.3.4'
Latest supported golden is `pari-2.3.5.tar.gz'
Picking golden version 2.3.5, file pari-2.3.5.tar.gz
Downloading `http://megrez.math.u-bordeaux.fr/pub/pari/OLD/2.3/pari-2.3.5.tar.gz'...
-> FAIL Timed out (> 60s). Use --verbose to retry.
-> N/A
-> FAIL Configure failed for Math-Pari-2.030518. See /root/.cpanm/work/1613073570.402/build.log for details.
Searching Crypt::Random () on cpanmetadb ...
--> Working on Crypt::Random
Fetching http://www.cpan.org/authors/id/V/VI/VIPUL/Crypt-Random-1.52.tar.gz
-> OK
Unpacking Crypt-Random-1.52.tar.gz
Entering Crypt-Random-1.52
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring Crypt-Random-1.52
Running Makefile.PL
Warning: prerequisite Math::Pari 2.001804 not found.
Warning: prerequisite Statistics::ChiSquare 1.0000 not found.
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Crypt::Random
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Math::Pari 2.001804 ... No
Checking if you have Statistics::ChiSquare 1.0000 ... No
Checking if you have Class::Loader 2.00 ... Yes (2.03)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.34)
==> Found dependencies: Math::Pari, Statistics::ChiSquare
Already tried Math::Pari. Skipping.
Searching Statistics::ChiSquare (1.0000) on cpanmetadb ...
--> Working on Statistics::ChiSquare
Fetching http://www.cpan.org/authors/id/D/DC/DCANTRELL/Statistics-ChiSquare-1.0000.tar.gz
-> OK
Unpacking Statistics-ChiSquare-1.0000.tar.gz
Entering Statistics-ChiSquare-1.0000
Checking configure dependencies from META.json
Checking if you have ExtUtils::MakeMaker 6.58 ... Yes (7.34)
Configuring Statistics-ChiSquare-1.0000
Running Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Statistics::ChiSquare
Writing MYMETA.yml and MYMETA.json
-> OK
Checking dependencies from MYMETA.json ...
Checking if you have Test::More 0.88 ... Yes (1.302133)
Checking if you have ExtUtils::MakeMaker 0 ... Yes (7.34)
Building Statistics-ChiSquare-1.0000
cp lib/Statistics/ChiSquare.pm blib/lib/Statistics/ChiSquare.pm
Manifying 1 pod document
Manifying 1 pod document
Installing /usr/local/share/perl/5.28.1/Statistics/ChiSquare.pm
Installing /usr/local/man/man3/Statistics::ChiSquare.3pm
Appending installation info to /usr/local/lib/aarch64-linux-gnu/perl/5.28.1/perllocal.pod
-> OK
Successfully installed Statistics-ChiSquare-1.0000
Installing /usr/local/share/perl/5.28.1/aarch64-linux-gnu-thread-multi/.meta/Statistics-ChiSquare-1.0000/install.json
Installing /usr/local/share/perl/5.28.1/aarch64-linux-gnu-thread-multi/.meta/Statistics-ChiSquare-1.0000/MYMETA.json
-> FAIL Installing the dependencies failed: Module 'Math::Pari' is not installed
-> FAIL Bailing out the installation for Crypt-Random-1.52.
```

Does anyone have an idea, what might be the issue here / what I'm doing wrong?

**Comment by donjonsn** [comment]
Math::Pari is often causing problems when it fails to compile, that is why Crypt::Random was removed again from the docker image. It should be pinned to a working/tested version. I installed Crypt::Random using the env `CPAN_PKGS: Crypt::Random` in my docker-compose.yaml and was lucky. The versions I have currently running are:
- Math::Pari 2.030518
- Crypt::Random 1.520
- Statistics::ChiSquare 1.000000

**Comment by bruzzz** [comment]
I tried it sever times, but it cancels the installation because of the timeout on configuration / fetch of the pari module.  At least in my case (when I do the installation manuelly, loging in into the container after its setup and executing "/usr/bin/perl -MCPAN -e 'install Crypt::Random'"), it takes quite a while. The installation of other modules works without any doubt.

@donjonsn What do you mean by `It should be pinned to a working/tested version`? How could I do that?

**Comment by donjonsn** [comment]
You seem to have a problem with the ftp download. According to [stackoverflow](https://stackoverflow.com/questions/66186976/cpan-fails-installing-module-mathpari-fetching-gp-pari), the server should be back up.

Installing like this pins the version (you need to pass the author).
- ILYAZ/Math-Pari-2.030518.tar.gz
- VIPUL/Crypt-Random-1.52.tar.gz
- DCANTRELL/Statistics-ChiSquare-1.0000.tar.gz

**Pull request merged**
